# Generated by Django 3.0.3 on 2020-02-16 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
